language: cpp

compiler:
  - gcc
  - clang

# Dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libtinyxml2-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

# Building
script: cd ./build && cmake && make
